'''''
numbers=[0,1,2,3,4,5,6,7]
print(numbers)
numbers=list(range(0,6))
print(numbers)
'''''
fruits=["apple","ornge","mango","banana"]
print(fruits[1:3])
print(fruits[0:4])
print(fruits[:4])
print(fruits[:3])
print(fruits[2:])